Resources:
  PetStorePostgreSQLRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "petstore_postgres"
  PetStoreFrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "petstore_frontend"

